Update to 7.0.10

diff --git a/docker-php-ext-enable b/docker-php-ext-enable
--- a/docker-php-ext-enable
+++ b/docker-php-ext-enable
@@ -1,44 +1,64 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 cd "$(php -r 'echo ini_get("extension_dir");')"
 
 usage() {
-	echo "usage: $0 module-name [module-name ...]"
+	echo "usage: $0 [options] module-name [module-name ...]"
 	echo "   ie: $0 gd mysqli"
 	echo "       $0 pdo pdo_mysql"
+	echo "       $0 --ini-name 0-apc.ini apcu apc"
 	echo
 	echo 'Possible values for module-name:'
 	echo $(find -maxdepth 1 -type f -name '*.so' -exec basename '{}' ';' | sort)
 }
 
-modules=()
-while [ $# -gt 0 ]; do
-	module="$1"
+opts="$(getopt -o 'h?' --long 'help,ini-name:' -- "$@" || { usage >&2 && false; })"
+eval set -- "$opts"
+
+iniName=
+while true; do
+	flag="$1"
 	shift
+	case "$flag" in
+		--help|-h|'-?') usage && exit 0 ;;
+		--ini-name) iniName="$1" && shift ;;
+		--) break ;;
+		*)
+			{
+				echo "error: unknown flag: $flag"
+				usage
+			} >&2
+			exit 1
+			;;
+	esac
+done
+
+modules=
+for module; do
 	if [ -z "$module" ]; then
 		continue
 	fi
-	if [ -f "$module.so" -a ! -f "$module" ]; then
+	if [ -f "$module.so" ] && ! [ -f "$module" ]; then
 		# allow ".so" to be optional
-		module+='.so'
+		module="$module.so"
 	fi
-	if [ ! -f "$module" ]; then
+	if ! [ -f "$module" ]; then
 		echo >&2 "error: $(readlink -f "$module") does not exist"
 		echo >&2
 		usage >&2
 		exit 1
 	fi
-	modules+=( "$module" )
+	modules="$modules $module"
 done
 
-if [ "${#modules[@]}" -eq 0 ]; then
+if [ -z "$modules" ]; then
 	usage >&2
 	exit 1
 fi
 
-for module in "${modules[@]}"; do
-	if grep -q zend_extension_entry "$module"; then
+for module in $modules; do
+	if nm -g "$module" | grep -q ' zend_extension_entry$'; then
 		# https://wiki.php.net/internals/extensions#loading_zend_extensions
 		line="zend_extension=$(readlink -f "$module")"
 	else
@@ -56,7 +76,7 @@ for module in "${modules[@]}"; do
 		continue
 	fi
 
-	ini="/usr/local/etc/php/conf.d/docker-php-ext-$ext.ini"
+	ini="/usr/local/etc/php/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
 	if ! grep -q "$line" "$ini" 2>/dev/null; then
 		echo "$line" >> "$ini"
 	fi
